### PR TITLE
#fixes notification id generation as a part of api ,soft delete in mogo db and typings in queue

### PR DESCRIPTION
**Pull request by Linoy339**

### CODE REVIEW

**Comment by Linoy339** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/115
https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/135

**Comment by avaidyam** [comment]
@Linoy339 Can you resolve the conflicts and I'll merge this PR too?

**Comment by Linoy339** [comment]
Its done @avaidyam. Can you check ?

**Comment by avaidyam** [comment]
@Linoy339 It says here in GitHub that there are still conflicts to be resolved, and I do not see any additional commits on this PR.

**Comment by Linoy339** [comment]
@avaidyam . Conflicts has been resolved

**Pull request merged**
