### PR TITLE
#fixes sensor_event batch update

### PR DESCRIPTION
**Pull request by Linoy339**
-applied limit to be inserted in sensor_event database

### CODE REVIEW

**Comment by avaidyam** [comment]
@Linoy339 @michaelmenon Can you please thoroughly test this and **share the code** you used to test it so that my team (cc @jlavoie9 @ryan-hays) can also test it on our end before this hits staging OR production?

**Comment by Linoy339** [comment]
@avaidyam We have tested using Jmeter tool. Can we give you the jmx file here ?

**Comment by Linoy339** [comment]
Also, we will test it thoroughly in our server. If you could do the merging, we can test it there too

**Comment by avaidyam** [comment]
@Linoy339 @michaelmenon I cannot merge this without you doing thorough testing locally **FIRST** and then **ALSO** sharing your testing code (i.e. python/javascript/shell commands) to indicate how it was tested. My team will then test it locally too.

**Comment by Linoy339** [comment]
Yes. We will do it @avaidyam . 
We  have not used any shell commands. Instead, we have used a testing  tool (jmeter) to go for high number of api calls with larger number of data. It was working and we are continuing it.
For example, we tried with 5000 users to call the api with 100 events each. 
We will tell our testing feedback it by tomorrow

**Comment by Linoy339** [comment]
@avaidyam . Attached is the test suite which we have used.

[LampSensorEvent03.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/files/6357222/LampSensorEvent03.zip)


We have tested with 1000 users with 117 events each in our server:
    https://lampv2.zcodemo.com:9093/participant/U5440992922/sensor_event

Please find the zip file attached. For this to run:'
1. Extract zip file attached
2.Install  Jmeter
3.In the file menu,  select open and browse jmx file obtained from the unzip. You can change the api if you need(now, it will be our api server)
4.Run 

We have increased number of users from 100 to 1000 gradually(by changing number of threads or loops) with same set of data

The testing done was success and the data were found to be inserted properly in redis as well as in database.

**Comment by avaidyam** [comment]
@Linoy339 @michaelmenon Thanks for the test case suite! I've merged the PR (should be up in staging soon).

@jlavoie9 Let's chat offline about setting up JMeter and running the test case.

**Pull request merged**
