### PR TITLE
#fixes ignore tags with target-* for admins in the list

### PR DESCRIPTION
**Pull request by Linoy339**

### CODE REVIEW

**Comment by Linoy339** [comment]
Here, I did it for avoiding the tags for admin with `origin = null & target = *`.  
i.e
If type_id is not null(`researcherid, participantid`), keep the `type_id` as it is 
else "null" (for origin as null, I am checking explicitly for"null",  so that, admin do not get these keys in attachment list. ).
Is there an alternative for "null" which you can suggest?

**Comment by avaidyam** [comment]
[No, this is incorrect. I meant these lines here.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L120)

**Comment by Linoy339** [comment]
Got it.  SO, we can remove :
1)[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L127](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L127)

2)[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L128](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L128)

 

Also, append the condition `{ _deleted: false, _parent: null, type: '*', key: attachment_key }` here :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L120](https://github.com/BIDMCDigitalPsychiatry/LAMP-
server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L120)

**Comment by Linoy339** [comment]
I apologize. Something went wrong. I will do it now

**Comment by Linoy339** [comment]
Just to confirm . The lines you mentioned is 

[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L120](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L120)

and not this one:  [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L162](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/e51373123e9f3bb780199dd29cbf425cfdcfaccd/src/repository/mongo/TypeRepository.ts#L162)

**Comment by carlan1** [comment]
If not implemented already please be sure that:

Running the command Tag.set(origin, target=*, key, value) will **not** set a tag on the **origin**, **regardless** of whether the origin is an admin, researcher, study, or participant.

**Review by avaidyam — APPROVED** [review]

**Pull request merged**
